[package]
name = "Way_Too_Long_Words"
version = "0.1.0"
authors = ["mohammed <slimani.med.21@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
